platform :ios, '9.0'
use_frameworks!

def shared_pods
    pod 'OktaAuthWithClientSecret'
    pod 'OktaAuthWithClientSecret', :path => '../', :commit => '8f16eee3d67f87114c4a93a926b110d08e6b37de'
end

target 'Okta_Example' do
  shared_pods
end

target 'Okta_Tests' do
  shared_pods
end

target 'Okta_UITests' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end
  end
end
